import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";
import { ApolloWrapper } from "../lib/apollo-wrrapper";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { CartProvider } from "@/app/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Navbar />
          <ApolloWrapper>{children}</ApolloWrapper>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
